import json

# ===============================
# Bereinigte Testfälle (ohne Namen)
# ===============================
testcases = [
    {"ID": "T1", "question": "Wann sind die Stand-Up-Meetings im HS 2025 geplant?", 
     "expected": "Der Chatbot sollte die „Vorläufige Agenda Stand-Ups HS 2025“ nennen (Datum, Themen, ggf. Links).", 
     "requirements": ["F1", "F2", "F3"]},
    {"ID": "T2", "question": "Was ist Peer Feedback im Edu-Lab-Kontext?", 
     "expected": "Erklärung, was Peer Feedback ist, Vorteile und Einsatz bei Bewertungen.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T3", "question": "Wie wird KI in der Lehre aus Sicht der HSLU I eingesetzt?", 
     "expected": "Beschreibung der Nutzung von KI durch Lehrpersonen: Zweck, Beispiele.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T4", "question": "Welche rechtlichen Fragen bestehen bei KI in der Schweiz laut dem Edu-Lab?", 
     "expected": "Darstellung von technischen, regulatorischen und rechtlichen Aspekten (Datenschutz, Cloud, AGB).", 
     "requirements": ["F1", "F2", "F3"]},
    {"ID": "T8", "question": "Welche neuen Lehrformate diskutiert das Edu-Lab im Blog?", 
     "expected": "Übersicht neuer Lehrformate: Hybridunterricht, KI-Nutzung, Stand-Ups etc.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T9", "question": "Was ist das Ziel der Edu-Lab Stand-Up Meetings?", 
     "expected": "Ziel: Organisation, Austausch, Themenkoordination.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T10", "question": "Wie wird Peer Feedback auf Dozierendenseite bewertet?", 
     "expected": "Befürwortung und Bedenken laut Blog.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T12", "question": "Welche Themen wurden im Stand-Up Meeting FS2025 behandelt?", 
     "expected": "Themen: KI-Plagiat, generative KI, Recht, Lernkarten etc.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T13", "question": "Wie viele Studierende waren am Peer-Feedback-Mechanismus beteiligt?", 
     "expected": "Falls erwähnt: Statistiken, Anzahl Teilnehmende, Erfahrungen.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T14", "question": "Wie beurteilt das Edu-Lab die Nachhaltigkeit von KI-Einsatz in der Lehre?", 
     "expected": "Einschätzung zu Nutzen, Risiken, ethischen Aspekten.", 
     "requirements": ["F1", "F3", "F4"]},
    {"ID": "T15", "question": "Gibt es eine Vision, wie KI in zukünftigen Projekten eingesetzt werden soll?", 
     "expected": "Zukunftsideen, strategische Vision, geplante Entwicklungen.", 
     "requirements": ["F1"]},
    {"ID": "T16", "question": "Welche Rolle spielt Lernkarten-Software in den Lehrszenarien des Edu-Labs?", 
     "expected": "Einsatz digitaler Lernkarten laut Blog.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T17", "question": "Was wurde im Stand-Up Meeting zum Hybridunterricht berichtet?", 
     "expected": "Chancen, Herausforderungen, Kulturwandel laut Blog.", 
     "requirements": ["F1", "F3", "F2"]},
    {"ID": "T18", "question": "Welche technischen Anforderungen müssen für den KI-Einsatz erfüllt sein?", 
     "expected": "Themen: Rechenleistung, Toolzugänge, Datenschutz, Cloud.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T19", "question": "Welche Risiken sieht das Edu-Lab beim Einsatz generativer KI?", 
     "expected": "Risiken: Halluzination, Datenschutz, fehlende Transparenz, Prüfungsrecht.", 
     "requirements": ["F1", "F4"]},
    {"ID": "T20", "question": "Wie unterscheidet sich die KI-Nutzung zwischen Studierenden und Dozierenden?", 
     "expected": "Analyse: verschiedene Nutzungshäufigkeit, Use Cases, Hindernisse.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T21", "question": "Welche positiven Beispiele für KI-gestützte Lehre werden im Blog genannt?", 
     "expected": "Best Practices aus mehreren Artikeln.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T23", "question": "Wie definiert das Edu-Lab ‚Kulturwandel‘ im Zusammenhang mit Hybridunterricht?", 
     "expected": "Beschreibung laut Artikel „Neue Lehrformate, neue Werte…“.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T24", "question": "Welche Themen wurden im Stand-Up Meeting HS 2024 besprochen?", 
     "expected": "Liste der Agenda-Punkte.", 
     "requirements": ["F1", "F3", "F2"]},
    {"ID": "T25", "question": "Welche Empfehlungen gibt es für Dozierende beim Einsatz von KI im Unterricht?", 
     "expected": "Didaktische Empfehlungen: Regeln, Transparenz, Lernziele.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T26", "question": "Welche Tools werden im Edu-Lab für kollaboratives Arbeiten erwähnt?", 
     "expected": "Miro, digitale Whiteboards, Peer-Feedback-Tools etc.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T28", "question": "Welche Herausforderungen sehen Dozierende beim Peer-Evaluation-Einsatz?", 
     "expected": "Objektivität, Zuverlässigkeit, Aufwand.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T29", "question": "Wie geht das Edu-Lab mit kritischem Feedback zu KI-Tools um?", 
     "expected": "Reflexionen in Stand-Ups und Blogartikeln.", 
     "requirements": ["F1", "N2"]},
    {"ID": "T30", "question": "Welche neuen Werte oder Kompetenzen erwartet das Edu-Lab in KI-gestützter Lehre?", 
     "expected": "Selbstverantwortung, Transparenz, digitale Medienkompetenz.", 
     "requirements": ["F1"]},
    {"ID": "T31", "question": "Welche erfolgreichen Experimentierprojekte gibt es im Edu-Lab?", 
     "expected": "Beispiele aus Pilotprojekten.", 
     "requirements": ["F1"]},
    {"ID": "T32", "question": "Wie wird im Edu-Lab Wissensaustausch zwischen Dozierenden organisiert?", 
     "expected": "Stand-Ups, Workshops, Peer-Feedback-Sessions.", 
     "requirements": ["F1"]},
    {"ID": "T33", "question": "Welche didaktischen Herausforderungen entstehen durch KI laut Blog?", 
     "expected": "Anleitung, Bewertung, Täuschungssicherheit.", 
     "requirements": ["F1", "F3"]},
    {"ID": "T34", "question": "Welche Blockchain-Projekte hat das Edu-Lab 2023 durchgeführt?", 
     "expected": "Keine Informationen vorhanden.", 
     "requirements": ["F1", "F4"]},
    {"ID": "T35", "question": "Wie kann der AI Thesis Coach bei der Strukturierung wissenschaftlicher Arbeiten helfen?", 
     "expected": "Gliederungsvorschläge, Kohärenz-Feedback.", 
     "requirements": ["F1"]},
    {"ID": "T36", "question": "Welche Vision hat das Edu-Lab für die Hochschullehre 2030?", 
     "expected": "Zukunftsperspektiven: Hybrid, KI-gestützt, personalisierte Lehre.", 
     "requirements": ["F1", "N2"]},
    {"ID": "T37", "question": "Kannst du mir erklären, wie das Peer-Feedback im Edu-Lab funktioniert?", 
     "expected": "Der Chatbot erkennt die deutsche Eingabe und antwortet vollständig auf Deutsch, basierend auf relevanten Blogartikeln.", 
     "requirements": ["F5", "F1", "F3"]},
    {"ID": "T38", "question": "What are the main challenges teachers face when using AI in the classroom according to the Edu-Lab blog?", 
     "expected": "Der Chatbot gibt eine Antwort auf Englisch, ohne Sprachen zu mischen, basierend auf englischen Übersetzungen der Inhalte.", 
     "requirements": ["F5", "F4"]},
    {"ID": "T39", "question": "Welche personenbezogenen Daten von Studierenden werden im Edu-Lab gespeichert?", 
     "expected": "Der Blog enthält keine Informationen über personenbezogene Daten von Studierenden. Dazu liegen keine Angaben vor.", 
     "requirements": ["N3", "F4", "F1"]},
]

# ===============================
# JSON-Datei speichern
# ===============================
with open("testcases.json", "w", encoding="utf-8") as f:
    json.dump(testcases, f, ensure_ascii=False, indent=4)

print("✅ testcases.json wurde erstellt!")
